// SHIKITYPE変換方式: OS IMEを数式から外し、raw英字を層ごとの候補集合へ送る回帰。
import { chromium } from '../spike/node_modules/playwright/index.mjs';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1180, height: 780 } });
const failures = []; let passed = 0;
function ok(label, value, detail = value) { if (value) { passed += 1; console.log(`  OK  ${label}`); } else { failures.push({ label, detail }); console.log(`  FAIL ${label}: ${JSON.stringify(detail)}`); } }
await page.goto(process.env.NEO_BASE ?? 'http://localhost:8893/app.html', { waitUntil: 'networkidle' });
await page.evaluate(() => { localStorage.clear(); window.__neoApp.setInputSystem('conversion', false); });
await page.reload({ waitUntil: 'networkidle' });
async function reset(layer = 'symbol') {
  await page.evaluate((wanted) => { const row = window.__neoApp.getActiveRow(); row.mf.value = ''; row.mf.executeCommand(['switchMode', 'math']); row.mf.position = 0; row.stack = []; row.run = []; row.runStack = []; row.history = []; row.nativeTextOpen = false; Object.assign(row.conversion, { raw: '', reading: '', searchReading: '', pending: '', navigation: false, selectedIndex: 0 }); row.conversion.preview.textContent = ''; row.conversion.preview.hidden = true; window.__neoApp.setInputSystem('conversion', false); for (let guard = 0; window.__neoApp.getBaseLayer() !== wanted && guard < 4; guard += 1) window.__neoApp.cycleBaseLayer(false); row.inputProxy.focus(); }, layer);
  // MathLiveの直前の直接入力から残るfocus/rAFを落ち着かせてから、専用proxyを検証する。
  await page.waitForTimeout(80);
}
async function conversion() { return page.evaluate(() => window.__neoApp.getConversionState()); }
async function value() { return page.evaluate(() => window.__neoApp.getActiveRow().mf.value); }
async function typeRaw(text) {
  for (const char of text.toUpperCase()) await page.keyboard.press(char === '-' ? 'Minus' : `Key${char}`);
}
console.log('\n== 変換層だけの専用IME・途中候補 ==');
await reset('symbol'); await typeRaw('x'); let state = await conversion(); ok('変換層のx一打は小文字xを絶対先頭候補にする', state.raw === 'x' && state.candidates[0] === 'latin-lower-x', state); await page.keyboard.press('Enter'); ok('x → Enterで小文字xを確定する', await value() === 'x', await value());
await reset('symbol'); await typeRaw('p'); state = await conversion(); ok('p一打は小文字pを先頭、対応するπを2番目にする', state.candidates[0] === 'latin-lower-p' && state.candidates[1] === 'pi', state); await page.keyboard.press('Enter'); ok('p → Enterでπではなく小文字pを確定する', await value() === 'p', await value());
await reset('symbol'); await typeRaw('a'); state = await conversion(); ok('a一打は英字・ギリシャ・英字下付き・ギリシャ下付きの順', state.candidates[0] === 'latin-lower-a' && state.candidates[1] === 'greek-alpha' && state.candidates[2].startsWith('shikitype-sub-latin-') && state.candidates[3].startsWith('shikitype-sub-greek-'), state);
await reset('symbol'); await typeRaw('x'); state = await conversion(); ok('既定受験辞書外のξもxの2番目候補に補う', state.candidates[0] === 'latin-lower-x' && state.candidates[1] === 'shikitype-greek-x' && state.candidates[2].startsWith('shikitype-sub-latin-') && state.candidates[3].startsWith('shikitype-sub-greek-'), state);
await reset('symbol'); await page.keyboard.press('Shift+KeyA'); state = await conversion(); ok('Shift+Aは大文字Aを先頭候補にする', state.raw === 'A' && state.candidates[0] === 'latin-uppercase-a', state); await page.keyboard.press('Enter'); ok('Shift+A → Enterで大文字Aを確定する', await value() === 'A', await value());
await reset('symbol'); await typeRaw('shitatsuki'); state = await conversion(); ok('したつきで下付き数字0〜9をすべて候補に出す', Array.from({ length: 10 }, (_, n) => `subscript-digit-${n}`).every((id) => state.candidates.includes(id)), state);
await reset('symbol'); await page.keyboard.press('Shift+Digit1'); ok('JIS Shift+1で!を直接入力する', (await value()).includes('!'), await value()); await page.keyboard.press('Minus'); await page.keyboard.press('Shift+Minus'); ok('-とShift+-で-と=を直接入力する', (await value()).includes('-') && (await value()).includes('='), await value());
await reset('symbol'); await page.keyboard.press('Shift+Digit8'); ok('JIS Shift+8で括弧構造を直接開く', (await value()).includes('\\left('), await value());
await reset('symbol'); await typeRaw('jyou'); state = await conversion(); ok('jyouでも累乗候補を出す', state.candidates.includes('power'), state);
await reset('symbol'); await typeRaw('zyou'); state = await conversion(); ok('zyouでも累乗候補を出す', state.candidates.includes('power'), state);
await reset('symbol'); await typeRaw('pai'); const beforeSpace = await conversion(); await page.keyboard.press('Space'); state = await conversion(); ok('物理Spaceは変換中に候補選択を開始し数式空白を入れない', state.raw === 'pai' && state.navigation && state.selectedIndex === 0 && JSON.stringify(state.candidates) === JSON.stringify(beforeSpace.candidates) && !(await value()).includes('\\,'), { beforeSpace, state, latex: await value() }); await page.keyboard.press('Space'); state = await conversion(); ok('変換中の物理Spaceをもう一度押すと次候補へ進む', state.raw === 'pai' && state.navigation && state.selectedIndex === 1 && !(await value()).includes('\\,'), { state, latex: await value() }); await page.keyboard.press('Enter'); ok('Space候補送り後は選択中候補を確定できる', Boolean(await value()), await value());
await reset('symbol'); await typeRaw('pai'); const beforeScreenSpace = await conversion(); await page.evaluate(() => window.__neoApp.handleVirtualSpecial('Space')); state = await conversion(); ok('画面Space相当も変換中は候補選択を開始し数式空白を入れない', state.raw === 'pai' && state.navigation && state.selectedIndex === 0 && JSON.stringify(state.candidates) === JSON.stringify(beforeScreenSpace.candidates) && !(await value()).includes('\\,'), { beforeScreenSpace, state, latex: await value() }); await page.evaluate(() => window.__neoApp.handleVirtualSpecial('Space')); state = await conversion(); ok('画面Space相当をもう一度押すと次候補へ進む', state.raw === 'pai' && state.navigation && state.selectedIndex === 1 && !(await value()).includes('\\,'), { state, latex: await value() }); await page.keyboard.press('Enter'); ok('画面Space候補送り後は選択中候補を確定できる', Boolean(await value()), await value());
await reset('symbol'); await page.keyboard.press('Space'); ok('変換入力が無い通常の物理Spaceは細い数式空白を入れる', (await value()).includes('\\,'), await value());
await reset('symbol'); await typeRaw('p');
const synchronousOwner = await page.evaluate(() => {
  const row = window.__neoApp.getActiveRow();
  const event = new KeyboardEvent('keydown', { code: 'KeyP', key: 'p', bubbles: true, cancelable: true });
  row.inputProxy.dispatchEvent(event);
  return { raw: row.conversion.raw, owner: row.conversion.shell.dataset.ownerRow, rowId: row.id };
});
ok('行モードは位置追従rAF前でも候補trayのowner rowを設定する', synchronousOwner.raw === 'pp' && synchronousOwner.owner === synchronousOwner.rowId, synchronousOwner);
let trayGeometry = await page.evaluate(() => {
  const row = window.__neoApp.getActiveRow();
  const tray = row.conversion.shell.getBoundingClientRect(); const sheet = document.getElementById('editor-sheet').getBoundingClientRect();
  return { tray, sheet, belowCaret: tray.top >= row.caret.getBoundingClientRect().bottom - 1, owner: row.conversion.shell.dataset.ownerRow === row.id };
});
ok('行モードの候補トレイはcaret直下かつ編集面の左右内に収まる', trayGeometry.belowCaret && trayGeometry.owner && trayGeometry.tray.left >= trayGeometry.sheet.left + 5 && trayGeometry.tray.right <= trayGeometry.sheet.right - 5, trayGeometry);
await page.setViewportSize({ width: 360, height: 780 }); await page.waitForTimeout(80);
trayGeometry = await page.evaluate(() => {
  const row = window.__neoApp.getActiveRow(); const tray = row.conversion.shell.getBoundingClientRect(); const sheet = document.getElementById('editor-sheet').getBoundingClientRect();
  return { tray, sheet, belowCaret: tray.top >= row.caret.getBoundingClientRect().bottom - 1, owner: row.conversion.shell.dataset.ownerRow === row.id };
});
ok('360px行モードでも候補トレイは編集面の左右にclipしない', trayGeometry.belowCaret && trayGeometry.owner && trayGeometry.tray.left >= trayGeometry.sheet.left + 5 && trayGeometry.tray.right <= trayGeometry.sheet.right - 5, trayGeometry);
await page.setViewportSize({ width: 1180, height: 780 }); await page.waitForTimeout(50);
await reset('symbol'); await typeRaw('pai'); state = await conversion(); ok('変換層のpaiはπ候補を出す', state.candidates[0] === 'pi', state); await page.keyboard.press('Enter'); ok('変換層のpai → Enterでπを確定する', (await value()).includes('\\pi'), await value());
await reset('symbol'); await typeRaw('pasento'); state = await conversion(); ok('pasentoは入力途中から%候補を保持する', state.candidates.includes('percent'), state); await page.keyboard.press('Enter'); ok('pasento → Enterで%を確定する', (await value()).includes('\\%'), await value());
await reset('symbol'); await typeRaw('integral'); state = await conversion(); ok('変換層のintegralは∫候補を出す', state.candidates.includes('integral') && state.raw === 'integral', state); await page.keyboard.press('Enter'); ok('変換層の∫を確定する', (await value()).includes('\\int'), await value());
await reset('symbol'); await typeRaw('lim'); state = await conversion(); ok('変換層のlimはlim候補を出す', state.candidates.includes('limit'), state);
for (const raw of ['g', 'gu', 'tegu']) { await reset('symbol'); await typeRaw(raw); state = await conversion(); ok(`${raw}は積分の語中一致で候補を出さない`, !state.candidates.includes('integral'), state); }
for (const raw of ['i', 'in', 'inte', 'integral', 's', 'seki', 'sekibun']) { await reset('symbol'); await typeRaw(raw); state = await conversion(); ok(`${raw}は積分aliasの語頭として候補を出す`, state.candidates.includes('integral'), state); }
await reset('symbol'); await typeRaw('p'); await page.keyboard.press('Tab'); state = await conversion(); ok('Tabでも別入力層へ移らず候補選択を開始する', state.raw === 'p' && state.navigation, state);
await reset('symbol'); const proxyFocus = await page.evaluate(() => { const row = window.__neoApp.getActiveRow(); return { proxy: document.activeElement === row.inputProxy, math: document.activeElement === row.mf }; }); ok('通常数式は非編集proxyへfocusを置きMathLiveへ置かない', proxyFocus.proxy && !proxyFocus.math, proxyFocus);
await page.evaluate(() => { const proxy = window.__neoApp.getActiveRow().inputProxy; for (const letter of 'INTEGRAL') proxy.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, cancelable: true, code: `Key${letter}`, key: 'Process', keyCode: 229 })); }); await page.waitForTimeout(40); state = await conversion(); const processResult = await page.evaluate(() => { const row = window.__neoApp.getActiveRow(); return { preview: row.conversion.preview.textContent, visible: [...row.conversion.list.querySelectorAll('.conversion-candidate')].map((node) => node.textContent), proxy: document.activeElement === row.inputProxy }; }); ok('日本語IME相当Processキーもcode由来英字integralとして∫候補を出す', state.raw === 'integral' && processResult.preview === 'integral' && processResult.visible.includes('∫') && processResult.proxy, { state, processResult });
const noCompositionLeak = await page.evaluate(() => { const row = window.__neoApp.getActiveRow(); const before = row.mf.value; row.mf.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true, cancelable: true })); row.mf.value = `${before}いんてぐらる`; row.mf.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true, cancelable: true, data: 'いんてぐらる' })); return { value: row.mf.value, raw: row.conversion.raw, proxy: document.activeElement === row.inputProxy }; }); ok('proxy中のcomposition文字は数式にもrawにも混入しない', noCompositionLeak.value === '' && noCompositionLeak.raw === 'integral' && noCompositionLeak.proxy, noCompositionLeak);
await reset('symbol'); await page.click('#text-entry-key'); await page.keyboard.type('hello'); await page.keyboard.press('Space'); await page.keyboard.type('world'); const textLatexWithSpace = await page.evaluate(() => window.__neoApp.getActiveRow().mf.value); ok('文内physical SpaceはOS標準の文章空白として残る', textLatexWithSpace.includes('hello world'), textLatexWithSpace); await page.keyboard.press('Enter');
await reset('symbol'); await page.click('#text-entry-key'); await page.keyboard.type('screen'); await page.evaluate(() => window.__neoApp.handleVirtualSpecial('Space')); await page.keyboard.type('space'); const textLatexWithScreenSpace = await page.evaluate(() => window.__neoApp.getActiveRow().mf.value); ok('文内画面Space相当も通常の文章空白として残る', textLatexWithScreenSpace.includes('screen space'), textLatexWithScreenSpace); await page.keyboard.press('Enter');
await reset('symbol'); await page.click('#text-entry-key'); await page.waitForTimeout(20); let textState = await page.evaluate(() => { const row = window.__neoApp.getActiveRow(); return { native: row.nativeTextOpen, focused: document.activeElement === row.mf || row.mf.contains(document.activeElement) }; }); ok('独立した文キー内だけはMathLiveへfocusして標準IMEを許可する', textState.native && textState.focused, textState); await page.keyboard.type('hello'); await page.keyboard.press('Enter'); await page.waitForTimeout(150); textState = await page.evaluate(() => { const row = window.__neoApp.getActiveRow(); return { native: row.nativeTextOpen, proxy: document.activeElement === row.inputProxy, value: row.mf.value }; }); ok('文内physical Enterは文を閉じ、次行を作らずproxyへ戻る', !textState.native && textState.proxy && textState.value.includes('\\text{hello}'), textState); await page.click('#text-entry-key'); await page.evaluate(() => window.__neoApp.handleVirtualSpecial('Enter')); await page.waitForTimeout(150); textState = await page.evaluate(() => { const row = window.__neoApp.getActiveRow(); return { native: row.nativeTextOpen, proxy: document.activeElement === row.inputProxy }; }); ok('文内画面Enter相当も文を閉じてproxyへ戻る', !textState.native && textState.proxy, textState);
await browser.close(); console.log(`\n${passed} passed, ${failures.length} failed`); if (failures.length) process.exitCode = 1;
